#!/usr/bin/env bash
# 100-Makefile

# Compiler and flags
CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic

# Executable name
NAME = school

# Source files
SRC = main.c school.c

# Object files
OBJ = $(SRC:.c=.o)

# Cleaner program
RM = /bin/rm

# Targets
all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $^ -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	$(RM) -f *~ $(NAME)

oclean:
	$(RM) -f $(OBJ)

fclean: clean oclean

re: fclean all

.PHONY: all clean oclean fclean re

# Check if m.h exists
ifeq ($(wildcard m.h),)
    $(error "m.h not found")
endif
