#!/usr/bin/env bash
# 100-Makefile

# Variables
CC = gcc
SRC = main.c school.c
OBJ = $(SRC:.c=.o)
NAME = school
CFLAGS = -Wall -Werror -Wextra -pedantic

# Rules
all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

main.o: main.c m.h
	$(CC) -c main.c

school.o: school.c m.h
	$(CC) -c school.c

clean:
	$(RM) *~ $(NAME)

oclean:
	$(RM) $(OBJ)

fclean: clean oclean

re: fclean all

.PHONY: all clean oclean fclean re
