#!/usr/bin/env bash
# 2-Makefile

# Variables
CC = gcc
SRC = main.c school.c
OBJ = $(SRC:.c=.o)
NAME = school

# Rule to build the executable
all: $(NAME)

# Rule to link the object files to create the executable
$(NAME): $(OBJ)
	$(CC) $(OBJ) -o $(NAME)

# Rule to compile the .c files into .o files
%.o: %.c
	$(CC) -c $< -o $@

# Clean up object files and executable
clean:
	rm -f $(OBJ) $(NAME)
